### ISSUE TITLE
maven缺少本地包，报错

### ISSUE THREAD

**Issue by Lovnx** [HQIT/tech-talk-spring-oauth2-jwt-zuul-ui-example#2]
导入工程后，提示这俩不存在
		<dependency>
			<groupId>com.cloume.common</groupId>
			<artifactId>common-rest-response</artifactId>
			<version>0.0.2-SNAPSHOT</version>
		</dependency>

		<dependency>
			<groupId>com.cloume.common</groupId>
			<artifactId>common-utils</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

**Comment by szhgoldeneye** [comment]
添加一下我们的远程仓库地址`https://github.com/HQIT/maven-repo`

**Comment by Lovnx** [comment]
好的，可以加个qq或者微信吗

**Comment by szhgoldeneye** [comment]
微信就是我github id

**Comment by SUGE2016** [comment]
``com.cloume.common`` ``common-rest-response``这是我们内部用的效率库
